### ISSUE TITLE
alpine:latest with known networking issues

### ISSUE THREAD

**Issue by jmacenka** [sthuber90/docker-speedtest#2]
The latest alpine:3.13 build has networking issues and was unable to resolve DNS queries correctly. When trying to feed the data to IndluxDB with curl I got "could not resolve indluxdb" error message. 
Even swaping out all references in the project to "influxdb:8086" with "instance-specific local Container-IP:8086" did not resolve the Problem.

This is a know issue with the latest alpine image: https://github.com/alpinelinux/docker-alpine/issues/135

If you just pin alpine to the previous Version  3.12 in your Dockerfile like this

FROM alpine:3.12

you can avoide the issue. This is the reccomendet temporary fix. I was researching my network and local DNS handling quite a bit before I found this :-)

Great project btw! After a long night of research and debugging its now running on my RPI3 and monitoring my Network ;-)

Greetings from Germany.

**Comment by sthuber90** [comment]
Thank you for bringing this to my attention again. The issue is actually not with alpine per se, but with the "old" _libseccomp_ version on raspbian systems that do not support time64 (see https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-762542148). For my personal Raspberry Pi I updated the _libseccomp_ version. However, I can understand if this is not the preferred way for everybody. Therefore, I followed your suggestions from https://github.com/sthuber90/docker-speedtest/issues/1#issuecomment-842972528 .

**Comment by sthuber90** [comment]
Let me know if the fix works for you, now 😄

**Comment by jmacenka** [comment]
**_EDIT: sorry, I spoke to early, see also second post below_**

Like a breeze now :-) thanks for the quick response.

<img width="960" alt="20210519_updating_and_redeploying" src="https://user-images.githubusercontent.com/36518907/118801380-3b5b0b80-b8a1-11eb-828a-f141d95f3f11.PNG">

<img width="960" alt="20210519_check_running" src="https://user-images.githubusercontent.com/36518907/118801668-8d9c2c80-b8a1-11eb-8570-81b94a2fd36a.PNG">

Had to adapt the y-range of your [pre-build Dashboard](https://github.com/sthuber90/docker-speedtest/blob/main/chronograf-speedtest-dashboard.json) to fit my connection speed :-P

<img width="960" alt="20210519_results" src="https://user-images.githubusercontent.com/36518907/118828312-710ded80-b8bd-11eb-8cab-637a256c4cc9.PNG">

**Comment by jmacenka** [comment]
Sorry, I spoke to early. The subsequent pulls of the same docker-instance yielded the error again, which is rather strange:

<img width="960" alt="20210519_Not_quite_yet" src="https://user-images.githubusercontent.com/36518907/118803213-5fb7e780-b8a3-11eb-83de-04d959207004.PNG">

Did you remember to push the newly build Docker-Image to [sthuber90/speedtest](https://hub.docker.com/r/sthuber90/speedtest/)?

It seems to work when I do this change in the docker-compose.yaml:

```
  speedtest:
#    image: sthuber90/speedtest
    build: .
    container_name: speedtest
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
```
Then again: maybe docker-compose does not check for later versions on Dockerhub and did not automatically re-download [sthuber90/speedtest:latest](https://hub.docker.com/r/sthuber90/speedtest/). A manual sync might do the trick and this would not be a problem for anybody just "cleanly" deploying the project.

`docker pull sthuber90/speedtest`

However it yielded another error but at least networking seems to be right subsequently:

<img width="960" alt="20210519_Not_quite_yet_2" src="https://user-images.githubusercontent.com/36518907/118806017-e0c4ae00-b8a6-11eb-98bf-23a99590bcb4.PNG">
