### ISSUE TITLE
Running on x86

### ISSUE THREAD

**Issue by rjcds** [sthuber90/docker-speedtest#4]
Hi I've tried to get this going on my x86 (x64) based Synology NAS (DS918)

I changed the Dockerfile source for speedtest to:

`wget -O speedtest-cli.tgz https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-x86_64-linux.tgz`

Influx and Grafana spin up without issue, but the speedtest container restarts continuously. The error is

`standard_init_linux.go:230: exec user process caused: exec format error`

Which is believe is an architecture error ? Is there something else I need to modify to get it going on x86 ?

**Comment by sthuber90** [comment]
Hi, I'm not familiar with the differences between x86 and arm on a detailed level. How are you starting the three containers? Do you use your locally built speedtest image?

**Comment by rjcds** [comment]
Rookie error - I was still loading your speedtest image from GitHub :)
Changed to my locally built image and working perfectly
Thanks for a great project !

**Comment by Gis70** [comment]
Hi @rjcds can you tell me which step did you do to make it working on x86 arch ? I'm facing the same issue, i change also the speedtest cli script by the one for x86 but still the error

thx

**Comment by rjcds** [comment]
Have you modified the docker-compose.yaml to point to your locally built x86 version of speedtest ? Otherwise I think it will pull the ARM one from this repo, and you'll get the architecture errors...

**Comment by Gis70** [comment]
Do you mean doing something there ? 
![image](https://user-images.githubusercontent.com/16589132/170353385-f903c6ab-3add-44fa-962f-681376bc8b0d.png)

I didn't modify it indeed, how can I specify my own image ?

**Comment by rjcds** [comment]
```  
speedtest:
#    image: sthuber90/speedtest
    build: /path/to/your-image/
```
