### ISSUE TITLE
Line+Stat shows 0

### ISSUE THREAD

**Issue by rjcds** [sthuber90/docker-speedtest#5]
The dashboard example ends up [displaying zero](https://github.com/sthuber90/docker-speedtest/blob/main/docs/img/dashboard.png) as the single stat for Latency and Packet Loss, regardless of the actual last value

I think it might be because of the FILL(null) at the end of the query, as per https://github.com/influxdata/chronograf/issues/1493

Changing it to FILL(none) seems to work for me

**Comment by sthuber90** [comment]
Thank you for bringing this to my attention. Do you have screenshots on how these settings differ in the output provided on the dahsboard?

**Comment by rjcds** [comment]
Sure - [here's my latest](https://ibb.co/H7y5GWQ)

The packet loss shows 0, I think because that was the most recent value (see highlighted value at the bottom)

**Comment by sthuber90** [comment]
Ah. Very well. I see what you mean. I'll draft a PR for it and see to get it changed in the repo by the end of this week 👍

**Comment by rjcds** [comment]
Thanks - and thanks for a great project

**Comment by sthuber90** [comment]
Thank you. Feel free to look through the PR and leave a comment if you think something is missing, otherwise I will go ahead an merge it. Closing this issue now
